### ISSUE TITLE
Error when enabling correlation loss

### ISSUE THREAD

**Issue by HaniItani** [CVMI-Lab/PAConv#1]
Hello @Dingry,

Thank you for sharing your great work. I managed to run the code on the task of semantic segmentation on S3DIS but without the correlation loss. Whenever I enable the correlation loss I get the following error:
`torch.nn.modules.module.ModuleAttributeError: 'PAConvCUDA' object has no attribute 'matrice1'` from line 203 in train.py.

Also can you please provide the preprocessing details of S3DIS and perhaps the scripts to generate the h5 files from raw S3DIS data files? That'd be much appreciated.

Thank you in advance.
Best regards,
Hani

**Comment by Dingry** [comment]
Hi, Hani,

Thanks for your interest in our work and for pointing out the bug. We have fixed it. Now the code should work fine. 

As far as the preprocessing of S3DIS, we used the processed data provided by the [PointWeb](https://github.com/hszhao/PointWeb) repo. As I understand it, each .h5 file contains 4096 points which are block-sampled from the original scenes. Unfortunately, I don't have the script for generating them. Maybe you can ask the authors of PointWeb. 

Thanks.

Best,
Runyu

**Comment by HaniItani** [comment]
Hello @Dingry,

Thank you very much for the prompt reply. I can confirm the code now runs fine with the correlation loss enabled. 
Regarding the data split, it's not very clear how to train/test per Area for 6 fold cross validation. Can you please provide the splits for every individual Area please. It's also not clarified in PointWeb repo.

Best regards,
Hani

**Comment by mutianxu** [comment]
Hi @HaniItani,

We will release the code for 6-fold validation very recently, so far you can refer to the result on Area-5 for the model performance.

Thanks,
Mutian

**Comment by mutianxu** [comment]
Hi @HaniItani ,

We have added the code for [6-fold validation](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/test_s3dis_6fold.py).

By using this, you should:

(1) Assume that you want to train on Area-2,3,4,5,6 and test on Area-1, you should first change the [test_area index](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/config/s3dis/s3dis_pointnet2_paconv.yaml#L7) in the config file to 1;
(2) Finish **full** train and test, the **test result files** of Area-1 will be saved in corresponding paths after the test;
(3) Repeat 1,2 by changing the test_area index to 2,3,4,5,6 respectively;
(4) Collect all the test result files of all areas to one directory and state the path to this directory at https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/test_s3dis_6fold.py#L52;
(5) Run the code for [6-fold validation](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/test_s3dis_6fold.py), you will get the final 6-fold results.

Hope this is helpful to you!

Best,
Mutian

**Comment by HaniItani** [comment]
Hi @mutianxu,

Thank you very much, this is really helpful. I'll close the issue for now and re-open it if I faced any other issues reproducing the results of your great work.

Many thanks for the prompt reply.
Best regards,
Hani
