### ISSUE TITLE
S3DIS preprocessing

### ISSUE THREAD

**Issue by honggudrnjs** [CVMI-Lab/PAConv#10]
First of all, thanks for sharing your amazing work and code.
By the way, we have a single question on S3DIS dataset preprocessing.
The size of S3DIS you provided is about 4GB, which is much lighter than standard S3DIS dataset (about 60 GB).
Could you share preprocessing method for the S3DIS dataset?

**Comment by Dingry** [comment]
Thanks for your comments.
We use the preprocessed dataset provided by [PointWeb](https://github.com/hszhao/PointWeb) since it is well-organized and easy to use. It merges the annotation and original points data. You may refer to [PointNet](https://github.com/charlesq34/pointnet/blob/master/sem_seg/collect_indoor3d_data.py). It provides the script for S3DIS preprocessing.

**Comment by honggudrnjs** [comment]
Thanks for your explanation! It helps a lot :)

**Comment by whuhxb** [comment]
@honggudrnjs 
Hi, 

    Do you know how to generate the .h files for S3DIS dataset in the downloaded dataset? Thanks a lot. Best wishes.

Xiaobing

**Comment by whuhxb** [comment]
@Dingry 
Hi,

   Do you know how to generate the .h files for S3DIS dataset in the downloaded dataset? Thanks a lot. Best wishes.

Xiaobing

**Comment by whuhxb** [comment]
@mutianxu 
Hi, 
    I have seen the code, this answer only merges the annotation and point cloud. But it does not include the generation of .h files. According to the downloaded S3DIS dataset, the .h files are generated by the author at first? I have no idea. Could you please provide what the .h files contain? or the code? Thanks a lot.

**Comment by Dingry** [comment]
Hi,
    Do you mean the .h5 files used in our methods? [PointNet](https://github.com/charlesq34/pointnet/blob/master/sem_seg/gen_indoor3d_h5.py) also preprocesses it, I think the processing code can be found in this repo.

**Comment by whuhxb** [comment]
Hi @Dingry ;
     I have generated the .h5 files now. But the number of .h5 files generated is not equal to the .h5 files downloaded. What's the difference? How to set the H5_BATCH_SIZE to make the generated .h5 files equal to downloaded files? Thanks.

**Comment by whuhxb** [comment]
Hi @Dingry ：
I only generated 24 .h files, but the author has provided 23585 .h files. I have no idea how to generate 23585 .h files. Could you please provide some information of generating 23585 .h files? Thanks a lot.

**Comment by whuhxb** [comment]
I have controled the H5_BATCH_SIZE setting as 2, but I can't obtain the files, with each of the same size, for example in the downloaded file of 150MB. The files I have generated have different sizes, for example 170MB or 140MB. Do you know how to control the size of the generated .h files?
