### ISSUE TITLE
cuda and non-cuda version

### ISSUE THREAD

**Issue by honggudrnjs** [CVMI-Lab/PAConv#15]
To begin with, thanks for sharing your awesome work :)
By the way, I see some differences between cuda and non-cuda version of your work.
They differ like the following:
1. The number of hidden layers are different
2. Learning rate decay scheduling differs (even different from what is mentioned in your paper)

I want you to make sure about this situation.
Thanks for your help in advance :)

**Comment by Dingry** [comment]
Thanks for your comments. 
We have tried both configs in  CUDA and non-CUDA versions. The performance gap is really small. The config difference doesn't matter too much in the two versions.  Our paper mainly describes the non-CUDA version config since it has the highest performance.
