### ISSUE TITLE
请问是1d卷积吗？请问怎样修改代码  轻量化之类的 我只会2d图像卷积。。

### ISSUE THREAD

**Issue by henbucuoshanghai** [CVMI-Lab/PAConv#17]
tks

**Comment by mutianxu** [comment]
The conv on 3D point clouds is different from 2D images, so far our code may be the best way to implement our methood.

**Comment by henbucuoshanghai** [comment]
tks for your kind reply.   
The conv on 3D point clouds is different from 2D images?what is the different.

but i wnat to chnage it smaller and with attention like senet in 2d conv  ?how?
please  tks

**Comment by mutianxu** [comment]
SENet learns the scores on each channel by: 1. Squeeze -> AvgPool on the feature input of an image to get the input ; 2. Excitation -> Use the output of step 1 as the input to an MLP, which outputs the channel-wise scores.
Thus, here you may try to use the idea in our work to learn scores, which means you can use our ScoreNet to replace the squeeze-excitation in SENet, vice versa.

**Comment by henbucuoshanghai** [comment]
very kind of you,very helpful.
the input's dimensions of&nbsp;ScoreNet is n,h,w,c?&nbsp; &nbsp;besides senet,the CBAM is also can be used here?
can you takes 10mins and give me a module !!!! thank you!!!!thankyou!!&nbsp;


besides, the Ghostnet in 2d conv&nbsp;&nbsp;can also be used here?&nbsp; how?


thank you
this is the last question.

**Comment by mutianxu** [comment]
The only thing I can tell you is that: ScoreNet's input is B N K D, where B is batch_size. N and K can be regarded as H W of 2D conv.

**Comment by henbucuoshanghai** [comment]
very kind and helpful.
 ScoreNet's input is B N K D, where B is batch_size. N and K can be regarded as H W of 2D conv.


the ScoreNet is a key module of paconv?&nbsp; the output of ScoreNet&nbsp; is&nbsp; B N K D too???


this is the last question ,thank you

**Comment by mutianxu** [comment]
The illustration of ScoreNet can be found in our paper, plz read carefully.
The output of ScoreNet is B N K M, where M is the number of weight matrices.

**Comment by henbucuoshanghai** [comment]
tks for all your help.


kind and helpful.
