### ISSUE TITLE
How to generate the .h files for S3DIS using .npy files? Could you share the code?

### ISSUE THREAD

**Issue by whuhxb** [CVMI-Lab/PAConv#19]
Hi Authors:

   How to generate the .h files for S3DIS dataset using .npy files? Could you please share the code for generating .h data format? Thanks a lot.

Xiaobing

**Comment by mutianxu** [comment]
You can refer to this [answer](https://github.com/CVMI-Lab/PAConv/issues/10).

**Comment by whuhxb** [comment]
@mutianxu 
OK. I see. Thanks a lot.
