### ISSUE TITLE
请问，DGCNN在ModelNet40的准确率不是92.2%吗，为什么你参考写的是92.9%？

### ISSUE THREAD

**Issue by swzaaaaaaa** [CVMI-Lab/PAConv#2]

**Comment by mutianxu** [comment]
Hi @swzaaaaaaa ,

Note that we refer to [the newest version](https://arxiv.org/pdf/1801.07829.pdf) of DGCNN in ACM Transactions on Graphics  2019, and the [corresponding code](https://github.com/WangYueFt/dgcnn/tree/master/pytorch).

Thanks,
Mutian
