### ISSUE TITLE
issue with classification

### ISSUE THREAD

**Issue by rabbiahassan** [CVMI-Lab/PAConv#22]
Hello !
your work is very interesting.When I tried to put the classification model on training it doesn't show any error,but it does get stuck here and doesn't proceed forward.Please tell me what is this issue?
Thanks for your time.
![image](https://user-images.githubusercontent.com/52703791/138566675-81d97d30-2a87-4fe7-a58b-4058dc86a4cc.png)

**Comment by meiqing0417** [comment]
Excuse me, I also encountered this problem. Is it solved now?

**Comment by brunotecgraf** [comment]
> Excuse me, I also encountered this problem. Is it solved now?

For me using the pointnet option worked!

**Comment by mutianxu** [comment]
> Ok, I have just run the code and the program runs normally with normal speed, while I use 4 3090Ti gpus or 4 2080Ti gpus under original batch_size.
> 
> As shown in your picture, I can make sure that the code is OK and you have compiled the cuda lib.
> 
> So as I mentioned before, this is caused by the very limited thread provided by your GPU (not only depended on the number of gpus but also the type of gpus).
> 
> What you can do now is to run on more gpus or better gpus to support our cuda_kernel.
