### ISSUE TITLE
Some questions about the "grouped_xyz" and “grouped_idx”

### ISSUE THREAD

**Issue by lin1061991611** [CVMI-Lab/PAConv#23]
Hello, I read two important value named  "grouped_xyz" and “grouped_idx” in /scene_seg/model/pointnet2/paconv.py ，and i can not understand it well, could you give some explanation ?

**Comment by Dingry** [comment]
Hi, in our code, _grouped_ refers to a set of points that are in the same local area. _Grouped_idx_ is the knn/ball-query index of each point and _grouped_xyz_ is the coordinates requested by _grouped_idx_.
