### ISSUE TITLE
Reproduction of PAConv_PointNet results on ModelNet40

### ISSUE THREAD

**Issue by haotian-liu** [CVMI-Lab/PAConv#26]
Dear authors,

Thank you for your great work.  I trained your PAConv_PointNet model (pointnet_paconv_train.yaml) on ModelNet40 dataset, and got results different from what is reported in the paper (93.2% w/o voting).  I got OA 92.4% with main_ddp.py and 92.7% with main.py.

The command I used: `python main.py --config config/pointnet_paconv_train.yaml`.

Could you please kindly advise if there is anything that I did not do correctly, or if you could kindly share your pre-trained model?  Thank you so much!

**Comment by mutianxu** [comment]
The code is right.

You can refer to [this answer](https://github.com/CVMI-Lab/PAConv/issues/9) for a similar problem.

**Comment by haotian-liu** [comment]
Thank you for explaining!  Would you mind sharing the pretrained PAConv model on ModelNet40 using PointNet?

**Comment by mutianxu** [comment]
I'm afraid I can not find it, but I can make sure that the code and result is right. And I recommend yo to use DGCNN_PAConv as the backbone.

**Comment by haotian-liu** [comment]
Thank you so much for your quick reply!  I will go ahead and take a look :)
