### ISSUE TITLE
About custom ops

### ISSUE THREAD

**Issue by Wuziyi616** [CVMI-Lab/PAConv#3]
I notice that in PointWeb, we need to compile the custom ops before running the code by `python setup.py install`. I don't see such instructions in this repo. So I wonder do we need to also compile the custom ops for paconv first? Thanks!

**Comment by Wuziyi616** [comment]
Indeed I run `python setup.py install` in `pointops/` and then successfully run the code. I think there is a small error in the config file you provided [here](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/config/s3dis/s3dis_pointnet2_paconv_cuda.yaml#L43). According to your provided pre-trained weight (CUDA-implemented PAConv which achieves 66.01 mIoU), I think this value should be `[16, 16, 16]`? I can't load the weight if I didn't modify that. Please correct me if I made any mistake. Thanks!

**Comment by Wuziyi616** [comment]
I know where I am wrong. The so-called `vanilla PAConv without CUDA` actually corresponds to `
s3dis_pointnet2_paconv_cuda.yaml `, while `CUDA-implemented PAConv` corresponds to `s3dis_pointnet2_paconv.yaml`? I have to say the filename is a little ambiguous though. I'd suggest you to add a link between each weight and its corresponding config file :)

**Comment by Dingry** [comment]
1. The custom ops can be loaded automatically without compiling. 
2. The link provided in README was confusing. I have already corrected it. Now the `CUDA-implemented PAConv` corresponds to the `s3dis_pointnet2_paconv_cuda.yaml` and `vanilla PAConv without CUDA` corresponds to the `s3dis_pointnet2_paconv.yaml `correctly.

Thanks for your comments! 
Runyu

**Comment by Wuziyi616** [comment]
Thanks for your reply. It solves my problem now :)
