### ISSUE TITLE
Visualization of Part Segmentation predictions

### ISSUE THREAD

**Issue by Ritchizh** [CVMI-Lab/PAConv#30]
Hi! I'm following your 3D Shape **Part Segmentation** work.
Could you please provide instuctions how to visualize predictions like in the paper:
<img src="https://user-images.githubusercontent.com/18049634/147676512-5e604993-1822-4b6d-9a5a-ba112f923824.jpg " width=600>
In main.py `test()` we get predictions for batches:
https://github.com/CVMI-Lab/PAConv/blob/696d36844e6b2f475f732579c24f67ae8059449d/part_seg/main.py#L370-L371
**How to combine them into predictions for an individual test file?**

**Comment by mutianxu** [comment]
Hi,

I use MatLab to visualize, you can also choose other tools.

For the progress:
1. Store the input 3d points (size b*n*3);
2. Store the predicted output (size b*n*50);
3. "project" the output into 3d points, where each point corresponds to a label. Each label will have different colors.

**Comment by Ritchizh** [comment]
@mutianxu thank you for the reply!
1. b - is the number of batches in 1 epoch? n - number of points in 1 batch? 
2. As I understand, 3 in input are RGB, 50 in output are labels.  `pred_choice = seg_pred.data.max(1)[1]`  will produce output of _bn1_, points coordinates should be the same as in input - what do you mean by projection?

**Comment by mutianxu** [comment]
> @mutianxu thank you for the reply!
> 
> 1. b - is the number of batches in 1 epoch? n - number of points in 1 batch?
> 2. As I understand, 3 in input are RGB, 50 in output are labels.  `pred_choice = seg_pred.data.max(1)[1]`  will produce output of _bn1_, points coordinates should be the same as in input - what do you mean by projection?

1. Yes
2. Projection means you use bn3 as the 3d coordinates of points, and use bn1 as the color of each point.
