### ISSUE TITLE
请问，在s3dis数据集的 without vote和with vote的测试代码，分别是哪个？

### ISSUE THREAD

**Issue by swzaaaaaaa** [CVMI-Lab/PAConv#31]

**Comment by Dingry** [comment]
Hi, we do not provide the voting scripts for semantic segmentation. The _tool/test_s3dis.py_ is for non-voting inference.

**Comment by swzaaaaaaa** [comment]
Can you privode the with-voting inference？Thanks.

**Comment by Dingry** [comment]
Hi, sorry that we do not write the voting script for semantic segmentation.

**Comment by gyy520cyaowu** [comment]
可以请教一下s3dis数据集要放在哪里吗，我总是似乎放不对，报错 0 samples
