### ISSUE TITLE
Visualization code of PAConv prediction results?

### ISSUE THREAD

**Issue by whuhxb** [CVMI-Lab/PAConv#34]
Hi, could you please provide the visualization code of PAConv prediction results? Thanks a lot.

**Comment by swzaaaaaaa** [comment]
Have you found a way to implement it?please.

**Comment by whuhxb** [comment]
@swzaaaaaaa 
Haven't yet.

**Comment by zouyanmei** [comment]
I have implemented it, but this code is only for predicted results and ground truth, not for raw input, you can use it as a test code.
[https://drive.google.com/file/d/1yz4v6sbzeRgypB_I4MgVN_FGysnyKGM4/view?usp=sharing](url)

**Comment by whuhxb** [comment]
@zouyanmei 

Hi, I'm sorry that I can't open the link.

**Comment by zouyanmei** [comment]
You can copy this link and open it with your browser.

**Comment by whuhxb** [comment]
@zouyanmei 

OK. Thanks.

**Comment by mutianxu** [comment]
Deal All,

The code for visualizing the segmentation result are also incorporated in [test_s3dis_6fold.py](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/test_s3dis_6fold.py) (called at line #55-#57).

Thanks for your attention!

Regards,
Mino

**Comment by whuhxb** [comment]
@mutianxu 
Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.

**Comment by mutianxu** [comment]
> @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.

Meshlab works for me.

**Comment by whuhxb** [comment]
> > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> 
> Meshlab works for me.

How to draw the semantic prediction figures in Figure 4? Also Meshlab?

**Comment by mutianxu** [comment]
> > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > 
> > 
> > Meshlab works for me.
> 
> How to draw the semantic prediction figures in Figure 4? Also Meshlab?

Screen shot on Meshlab.

**Comment by whuhxb** [comment]
> > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > 
> > > 
> > > Meshlab works for me.
> > 
> > 
> > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> 
> Screen shot on Meshlab.

How to the background color to White？ Thanks.

**Comment by mutianxu** [comment]
> > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > 
> > > > 
> > > > Meshlab works for me.
> > > 
> > > 
> > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > 
> > 
> > Screen shot on Meshlab.
> 
> How to the background color Blue&Purple to White？ Thanks.

That could be a trick on Meshlab.

**Comment by whuhxb** [comment]
> > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > 
> > > > > 
> > > > > Meshlab works for me.
> > > > 
> > > > 
> > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > 
> > > 
> > > Screen shot on Meshlab.
> > 
> > 
> > How to the background color Blue&Purple to White？ Thanks.
> 
> That could be a trick on Meshlab.

Could you share how to operate? Thanks. tools->options-choose white, right?

**Comment by whuhxb** [comment]
> > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > 
> > > > > 
> > > > > Meshlab works for me.
> > > > 
> > > > 
> > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > 
> > > 
> > > Screen shot on Meshlab.
> > 
> > 
> > How to the background color Blue&Purple to White？ Thanks.
> 
> That could be a trick on Meshlab.

Hi，I still can't turn the background color into white. Could you please share the operation? And, which version of Meshlab you used? Thanks a lot.

**Comment by mutianxu** [comment]
> > > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > > 
> > > > > > 
> > > > > > Meshlab works for me.
> > > > > 
> > > > > 
> > > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > > 
> > > > 
> > > > Screen shot on Meshlab.
> > > 
> > > 
> > > How to the background color Blue&Purple to White？ Thanks.
> > 
> > 
> > That could be a trick on Meshlab.
> 
> Hi，I still can't turn the background color into white. Could you please share the operation? And, which version of Meshlab you used? Thanks a lot.

I forgot ..., sorry. Plz google.

**Comment by whuhxb** [comment]
> > > > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > > > 
> > > > > > > 
> > > > > > > Meshlab works for me.
> > > > > > 
> > > > > > 
> > > > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > > > 
> > > > > 
> > > > > Screen shot on Meshlab.
> > > > 
> > > > 
> > > > How to the background color Blue&Purple to White？ Thanks.
> > > 
> > > 
> > > That could be a trick on Meshlab.
> > 
> > 
> > Hi，I still can't turn the background color into white. Could you please share the operation? And, which version of Meshlab you used? Thanks a lot.
> 
> I forgot ..., sorry. Plz google.

Have google. No proper answer.

**Comment by whuhxb** [comment]
> > > > > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Meshlab works for me.
> > > > > > > 
> > > > > > > 
> > > > > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > > > > 
> > > > > > 
> > > > > > Screen shot on Meshlab.
> > > > > 
> > > > > 
> > > > > How to the background color Blue&Purple to White？ Thanks.
> > > > 
> > > > 
> > > > That could be a trick on Meshlab.
> > > 
> > > 
> > > Hi，I still can't turn the background color into white. Could you please share the operation? And, which version of Meshlab you used? Thanks a lot.
> > 
> > 
> > I forgot ..., sorry. Plz google.
> 
> Have googled. No useful answer.

Solved. Thanks.

**Comment by whuhxb** [comment]
> > > > > > > > > > @mutianxu Use open3d to visualize the obj file? or Meshlab? Or what software? Thanks.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Meshlab works for me.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > How to draw the semantic prediction figures in Figure 4? Also Meshlab?
> > > > > > > 
> > > > > > > 
> > > > > > > Screen shot on Meshlab.
> > > > > > 
> > > > > > 
> > > > > > How to the background color Blue&Purple to White？ Thanks.
> > > > > 
> > > > > 
> > > > > That could be a trick on Meshlab.
> > > > 
> > > > 
> > > > Hi，I still can't turn the background color into white. Could you please share the operation? And, which version of Meshlab you used? Thanks a lot.
> > > 
> > > 
> > > I forgot ..., sorry. Plz google.
> > 
> > 
> > Have googled. No useful answer.
> 
> Solved. Thanks.

But the color of point clouds in Meshlab seem too dark, not bright. What the problem is?
