### ISSUE TITLE
Hello, can you share the visualized code of S3DIS data set and forecast results?  

### ISSUE THREAD

**Issue by swzaaaaaaa** [CVMI-Lab/PAConv#36]
Hello, can you share the visualized code of S3DIS data set and forecast results?  Thanks.

**Comment by zouyanmei** [comment]
I have implemented it, but this code is only for predicted results and ground truth, not for raw input, you can use it as a test code.
[https://drive.google.com/file/d/1yz4v6sbzeRgypB_I4MgVN_FGysnyKGM4/view?usp=sharing](url).
the input can refer t

**Comment by swzaaaaaaa** [comment]
The link is broken.

**Comment by zouyanmei** [comment]
You can copy this link and open it with your browser.

**Comment by mutianxu** [comment]
The code for visualizing the segmentation result is incorporated in [test_s3dis_6fold.py](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/test_s3dis_6fold.py) (called at line #55-#57).
