### ISSUE TITLE
Hello, author, how long will it take to load DGCNN for the first time?

### ISSUE THREAD

**Issue by shuaiqikai** [CVMI-Lab/PAConv#40]

**Comment by shuaiqikai** [comment]
I only have one GPU and am still loading for an hour at the moment.

**Comment by mutianxu** [comment]
Try to increase the number of your GPUs, or reduce the batch_size, the reason is indicated [here.](https://github.com/CVMI-Lab/PAConv/issues/22#issuecomment-950777090)

**Comment by mutianxu** [comment]
> I only have one GPU and am still loading for an hour at the moment.

Try to increase the number of your GPUs, or reduce the batch_size, the reason is indicated https://github.com/CVMI-Lab/PAConv/issues/22#issuecomment-950777090
