### ISSUE TITLE
Why set npoints=None for Sampling layer in pointnet2_paconv_seg.py?

### ISSUE THREAD

**Issue by whuhxb** [CVMI-Lab/PAConv#41]
Hi @mutianxu 

I go through the seg code, and have one question. Why the points for sampling layer is set to None for paconv? Do you mean setting the npoint to the original point number in all the sampling layer?

In the paper, it's said that replacing MLP with PAConv. But, actually, PAConv is used in sampling layer?  

https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/model/pointnet2/pointnet2_paconv_seg.py#L28

**Comment by mutianxu** [comment]
None means not specify the concrete number of points after downsampling. When it sets to none, the points are downsampled by 1/4, as [here](https://github.com/CVMI-Lab/PAConv/blob/01690b2e5aa023a30183f0efd0df9e7fe2919529/scene_seg/model/pointnet2/pointnet2_paconv_modules.py#L37)

I would be appreciated if you can read our code logic very carefully before opening an issue.

Thanks a lot!
Mino

**Comment by whuhxb** [comment]
Hi @mutianxu 

Thanks a lot for your kind answering.
