### ISSUE TITLE
Questions about `knn` and `knn_heap`

### ISSUE THREAD

**Issue by Wuziyi616** [CVMI-Lab/PAConv#6]
Hi, I found out that you use `knn_heap` instead of `knn` [here](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/lib/pointops/functions/pointops.py#L565-L566). I have never seen `knn_heap` before, so I wonder how much speed improvement does this operation bring about compared to `knn`? Besides, if I understand correctly, using `knn` or `knn_heap` will only affect speed but not performance right?

Another question is that, in the original PointNet++ paper, they use `ball query` instead of `knn`, which means the `radius` is not None [here](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/lib/pointops/functions/pointops.py#L561). So I wonder did you tried `ball query` in PAConv? Is `knn` better than `ball query` in PAConv?

Thank you so much for your time!

**Comment by Wuziyi616** [comment]
This is from the PointNet++ paper, just FYI:
```
...Ball query finds all points that are within a radius to the query point (an upper limit of K is set in
implementation). An alternative range query is K nearest neighbor (kNN) search...
```

**Comment by Wuziyi616** [comment]
I have tested knn myself and the speed improvement is amazing. My only question now is why you use knn instead of ball query?

**Comment by Dingry** [comment]
Thanks for your comments!

1. We use KNN for simplicity and generalizability since ball query has to tune radius in different layers on different dataset. We can try ball query yourself.
2. In our experiments, knn heap reduces the computation complexity without harming the performance. I am wondering did you find knn is quicker than knn heap?

Best,
Runyu

**Comment by Wuziyi616** [comment]
Thank you for your quick reply! Sorry for the confusion of my words, I meant `knn_heap` is amazing :)

**Comment by DapengFeng** [comment]
Hi, is there any tutorial about the `knn_heap`? I want to learn the kNN algorithm and the parallel implementation. Thank you so much for your time!
