### ISSUE TITLE
question about 'gpconv_cuda'

### ISSUE THREAD

**Issue by MrAirplaneLu** [CVMI-Lab/PAConv#7]
when I use Part Segmentation,it can't build the CUDA kernel

![image](https://user-images.githubusercontent.com/45754132/119607469-fe55c280-be26-11eb-9f2f-b119e015fbfb.png)
 
what can I do?
Thanks!

**Comment by haoranD** [comment]
Hi, I also got this problem. Can you please tell me how you solved it?

**Comment by haoranD** [comment]
> when I use Part Segmentation,it can't build the CUDA kernel
> 
> ![image](https://user-images.githubusercontent.com/45754132/119607469-fe55c280-be26-11eb-9f2f-b119e015fbfb.png)
> 
> what can I do?
> Thanks!

hi, I met same problem, can you please tell me how you solved it?

**Comment by haoranD** [comment]
> when I use Part Segmentation,it can't build the CUDA kernel
> 
> ![image](https://user-images.githubusercontent.com/45754132/119607469-fe55c280-be26-11eb-9f2f-b119e015fbfb.png)
> 
> what can I do?
> Thanks!

hi bro

**Comment by swzaaaaaaa** [comment]
hi, I met same problem, can you please tell me how you solved it?

> hi, I met same problem, can you please tell me how you solved it?

 I met same problem, can you please tell me how you solved it?

**Comment by iTomxy** [comment]
I encountered this problem, too. But it disappears as I run again (*amazing*). Then the program throws another error related to ninja, which I solved following the instructions in [Ninja is required to load C++ extensions | 问题解决](https://blog.csdn.net/zhiweihongyan1/article/details/121975628).
