### ISSUE TITLE
Strange `if` condition in the code?

### ISSUE THREAD

**Issue by Wuziyi616** [CVMI-Lab/PAConv#8]
Hi, I have read through your code and understand most of the it. However, I find one `if` condition very strange [here](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/util/paconv_util.py#L69). May I ask when will this `if` be triggered? What is it used for? Thanks!

If I understand correctly, `in_feat_trans[:, :, :3]` corresponds to the `xyz` of these points. Is it to compensate when input to the network is only xyz without rgb or other info, so that features is just `xyz`, and `in_feat - in_feat_c` will cause a zero?

**Comment by Dingry** [comment]
Thanks for your for our code. 
The `if` condition is to handle the issue when only `xyz` is the feature in the first layer. Since the CUDA version is more complicated in computing (xyz-xyz_c), we use this `if` here. 
If we find better implementations here, we will update them.

**Comment by Wuziyi616** [comment]
Thank you for your reply! That solves my questions perfectly.
